export const HTMLElements = [
"!DOCTYPE",
"a",
"abbr",
"acronym",
"address",
"applet",
"area",
"article",
"aside",
"audio",
"b",
"base",
"basefont",
"bdi",
"bdo",
"big",
"blockquote",
"body",
"br",
"button",
"canvas",
"caption",
"center",
"cite",
"code",
"col",
"colgroup",
"data",
"datalist",
"dd",
"del",
"details",
"dfn",
"dialog",
"dir",
"div",
"dl",
"dt",
"em",
"embed",
"fieldset",
"figcaption",
"figure",
"font",
"footer",
"form",
"frame",
"frameset",
"h1",
"h2",
"h3",
"h4",
"h5",
"h6",
"head",
"header",
"hr",
"html",
"i",
"iframe",
"img",
"input",
"ins",
"kbd",
"label",
"legend",
"li",
"link",
"main",
"map",
"mark",
"meta",
"meter",
"nav",
"noframes",
"noscript",
"object",
"ol",
"optgroup",
"option",
"output",
"p",
"param",
"picture",
"pre",
"progress",
"q",
"rp",
"rt",
"ruby",
"s",
"samp",
"script",
"section",
"select",
"small",
"source",
"span",
"strike",
"strong",
"style",
"sub",
"summary",
"sup",
"svg",
"table",
"tbody",
"td",
"template",
"textarea",
"tfoot",
"th",
"thead",
"time",
"title",
"tr",
"track",
"tt",
"u",
"ul",
"var",
"video",
"wbr"
] as const    
export type HTMLAttributes = {
accept? : string,
accesskey? : string,
action? : string,
align? : string,
alt? : string,
async? : string,
autocomplete? : string,
autofocus? : string,
autoplay? : string,
bgcolor? : string,
border? : string,
charset? : string,
checked? : string,
cite? : string,
class? : string,
color? : string,
cols? : string,
colspan? : string,
content? : string,
contenteditable? : string,
controls? : string,
coords? : string,
data? : string,
datetime? : string,
default? : string,
defer? : string,
dir? : string,
dirname? : string,
disabled? : string,
download? : string,
draggable? : string,
enctype? : string,
for? : string,
form? : string,
formaction? : string,
headers? : string,
height? : string,
hidden? : string,
high? : string,
href? : string,
hreflang? : string,
id? : string,
ismap? : string,
kind? : string,
label? : string,
lang? : string,
list? : string,
loop? : string,
low? : string,
max? : string,
maxlength? : string,
media? : string,
method? : string,
min? : string,
multiple? : string,
muted? : string,
name? : string,
novalidate? : string,
onabort? : string,
onafterprint? : string,
onbeforeprint? : string,
onbeforeunload? : string,
onblur? : string,
oncanplay? : string,
oncanplaythrough? : string,
onchange? : string,
onclick? : string,
oncontextmenu? : string,
oncopy? : string,
oncuechange? : string,
oncut? : string,
ondblclick? : string,
ondrag? : string,
ondragend? : string,
ondragenter? : string,
ondragleave? : string,
ondragover? : string,
ondragstart? : string,
ondrop? : string,
ondurationchange? : string,
onemptied? : string,
onended? : string,
onerror? : string,
onfocus? : string,
onhashchange? : string,
oninput? : string,
oninvalid? : string,
onkeydown? : string,
onkeypress? : string,
onkeyup? : string,
onload? : string,
onloadeddata? : string,
onloadedmetadata? : string,
onloadstart? : string,
onmousedown? : string,
onmousemove? : string,
onmouseout? : string,
onmouseover? : string,
onmouseup? : string,
onmousewheel? : string,
onoffline? : string,
ononline? : string,
onpagehide? : string,
onpageshow? : string,
onpaste? : string,
onpause? : string,
onplay? : string,
onplaying? : string,
onpopstate? : string,
onprogress? : string,
onratechange? : string,
onreset? : string,
onresize? : string,
onscroll? : string,
onsearch? : string,
onseeked? : string,
onseeking? : string,
onselect? : string,
onstalled? : string,
onstorage? : string,
onsubmit? : string,
onsuspend? : string,
ontimeupdate? : string,
ontoggle? : string,
onunload? : string,
onvolumechange? : string,
onwaiting? : string,
onwheel? : string,
open? : string,
optimum? : string,
pattern? : string,
placeholder? : string,
poster? : string,
preload? : string,
readonly? : string,
rel? : string,
required? : string,
reversed? : string,
rows? : string,
rowspan? : string,
sandbox? : string,
scope? : string,
selected? : string,
shape? : string,
size? : string,
sizes? : string,
span? : string,
spellcheck? : string,
src? : string,
srcdoc? : string,
srclang? : string,
srcset? : string,
start? : string,
step? : string,
style? : string,
tabindex? : string,
target? : string,
title? : string,
translate? : string,
type? : string,
usemap? : string,
value? : string,
width? : string,
wrap? : string,
}